---
- name: Ensure fail2ban is installed
  ansible.builtin.package:
    name: fail2ban
    state: present

- name: Ensure fail2ban is enabled and running
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

# ggf. Konfig anpassen + notify
# - name: Deploy jail.local
#   ...
#   notify: restart fail2ban
