---
- name: Ensure firewalld is installed
  ansible.builtin.package:
    name: firewalld
    state: present

- name: Ensure firewalld is enabled and running
  ansible.builtin.service:
    name: firewalld
    enabled: true
    state: started

- name: Open SSH port in firewalld
  ansible.posix.firewalld:
    port: "{{ firewall_ssh_port }}/tcp"
    permanent: true
    state: enabled
    immediate: true
    zone: "{{ firewall_default_zone }}"

- name: Open WireGuard port in firewalld
  ansible.posix.firewalld:
    port: "{{ firewall_wireguard_port }}/udp"
    permanent: true
    state: "{{ 'enabled' if firewall_enable_wireguard else 'disabled' }}"
    immediate: true
    zone: "{{ firewall_default_zone }}"
